project_id = "ejnqypkykyuguovunrsi"

[functions.job-discovery]
verify_jwt = false

[functions.score-jobs]
verify_jwt = false

[functions.extract-salaries]
verify_jwt = false

[functions.tailor-resume]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.generate-resume-pdf]
verify_jwt = false
